spring.application.name=taskmanager_service
spring.cloud.gcp.credentials.enabled=false
spring.cloud.gcp.firestore.enabled=true
spring.main.allow-bean-definition-overriding=true
spring.cloud.gcp.credentials.location=file:D:/Java/taskmanager_service/GOOGLE_APPLICATION/dogwood-thought-441315-n9-65ef9c3b3c42.json
spring.cloud.gcp.project-id=dogwood-thought-441315-n9
server.port=8080
logging.level.com.example.taskmanager=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.cloud.gcp.firestore.emulator.enabled=true
# Explicitly set the host and port instead of using environment variable
spring.cloud.gcp.firestore.host-port=localhost:8080